export const GET_ALL_PRODUCTS = 'CC/landing/GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_REQUESTED = 'CC/landing/GET_ALL_PRODUCTS_REQUESTED';
export const GET_ALL_PRODUCTS_COMPLETED = 'CC/landing/GET_ALL_PRODUCTS_COMPLETED';
export const GET_ALL_PRODUCTS_FAILED = 'CC/landing/GET_ALL_PRODUCTS_FAILED';