export const GET_PRODUCT_DETAILS = 'CC/productDetails/GET_PRODUCT_DETAILS';
export const GET_PRODUCT_DETAILS_COMPLETED = 'CC/productDetails/GET_PRODUCT_DETAILS_COMPLETED';
export const GET_PRODUCT_DETAILS_FAILED = 'CC/productDetails/GET_PRODUCT_DETAILS_FAILED';
export const INCREASE_QUANTITY = 'CC/productDetails/INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'CC/productDetails/DECREASE_QUANTITY';
