export const GET_PRODUCT_DETAILS = 'CC/landing/GET_PRODUCT_DETAILS';
export const GET_PRODUCT_DETAILS_COMPLETED = 'CC/landing/GET_PRODUCT_DETAILS_COMPLETED';
export const GET_PRODUCT_DETAILS_FAILED = 'CC/landing/GET_PRODUCT_DETAILS_FAILED';
